### ISSUE TITLE
Add severalUpdates function?

### ISSUE THREAD

**Issue by jvoigtlaender** [ccapndave/elm-update-extra#2]
Would you be interested to host the following function in this package?
```elm
severalUpdates : (msg -> model -> (model, Cmd msg)) -> List msg -> model -> (model, Cmd msg)
```
Originally raised as https://github.com/evancz/start-app/issues/40, and currently considered at https://github.com/elm-community/Manifesto/issues/34, but actually a nice fit for your existing package.

**Comment by ccapndave** [comment]
Yes, certainly! I'm not totally sure about the name though, although I must admit I'm finding it hard to think of anything better right now.

**Comment by jvoigtlaender** [comment]
Maybe `multiUpdate`?

**Comment by jvoigtlaender** [comment]
See #4.
